name: task_management_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.4
  ionicons: 0.1.2
  firebase_core: 1.20.0
  firebase_auth: 3.6.2
  google_sign_in: 5.4.0
  firebase_auth_web: 4.2.2
  firebase_core_web: ^1.7.1
  flutterfire_cli: ^0.2.4
  cloud_firestore: 3.4.3
  flutter: 
    sdk: flutter
  obx: ^0.1.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true

