// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhJeOZ6phiKIO7DzqKseEOkV_S54Uht8Y',
    appId: '1:74514712230:web:b0f03c60f4038027cd1667',
    messagingSenderId: '74514712230',
    projectId: 'task-management-app-20e35',
    authDomain: 'task-management-app-20e35.firebaseapp.com',
    storageBucket: 'task-management-app-20e35.appspot.com',
    measurementId: 'G-FW68G4DW7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxFVCGyAi9Xcr0KHxhgVPaODPJHiEkA00',
    appId: '1:74514712230:android:928d367adb6426bbcd1667',
    messagingSenderId: '74514712230',
    projectId: 'task-management-app-20e35',
    storageBucket: 'task-management-app-20e35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6TKAwMcRuH_ZsbZfvSZWoBdLsLb1QkEA',
    appId: '1:74514712230:ios:263ba19ac94f591ccd1667',
    messagingSenderId: '74514712230',
    projectId: 'task-management-app-20e35',
    storageBucket: 'task-management-app-20e35.appspot.com',
    androidClientId: '74514712230-55vasch9h35v89aj33srqlc2b3jff1n4.apps.googleusercontent.com',
    iosClientId: '74514712230-v9unqo5euj6cp5cn183k7u48d17mp55i.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6TKAwMcRuH_ZsbZfvSZWoBdLsLb1QkEA',
    appId: '1:74514712230:ios:263ba19ac94f591ccd1667',
    messagingSenderId: '74514712230',
    projectId: 'task-management-app-20e35',
    storageBucket: 'task-management-app-20e35.appspot.com',
    androidClientId: '74514712230-55vasch9h35v89aj33srqlc2b3jff1n4.apps.googleusercontent.com',
    iosClientId: '74514712230-v9unqo5euj6cp5cn183k7u48d17mp55i.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );
}
